import type { Metadata } from "next";
import { Providers } from "./providers";
import "./globals.css";
import Head from "next/head";
import { NavBar } from "./components/NavBar";
import { DemoBanner } from "./components/DemoBanner";
import { Footer } from "./components/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        <title>Cake Shop | Great Taste</title>
      </Head>
      <header>
        <NavBar/>
        <DemoBanner/>
      </header>
      <body>
        <Providers>{children}</Providers>
      </body>
      <footer>
        <Footer/>
      </footer>
    </html>
  );
}
